networks:
  ocrvnet:
    driver: bridge
services:
  azure-form-recognizer-read:
    container_name: azure-form-recognizer-read
    environment:
    - EULA=accept
    - billing=https://ces-ai-services.cognitiveservices.azure.com/
    - apiKey=4dfe6939ce944e77a8d5a6ede0453244
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/read-3.1
    networks:
    - ocrvnet
    ports:
    - 5000:5000
version: '3.9'
